import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './hooks/SessionProviders'
import NavBar from './components/Navbars'
import ThemeProviderHook from "./hooks/ThemeProviders";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
      <html lang="en">
        <body className={`${inter.className} dark:bg-[#000000] bg-white w-screen h-screen`}>
            <AuthProvider>
              <ThemeProviderHook>
                <NavBar />
                {children}
              </ThemeProviderHook>
            </AuthProvider>
        </body>
      </html>
    
  )
}
