import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '../utils/hooks/SessionProviders'
import ResponsiveAppBar from '@/components/TestNavBars'
import { ThemeProviderCustom } from '../utils/hooks/ThemeProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
      <html lang="en">
        <body className={`${inter.className} dark:bg-[#000000] bg-white w-screen h-screen`}>
          <div className='main'>
            <div className='gradient' />
          </div>
            <AuthProvider>
              <ThemeProviderCustom>
                <main className='app'>
                  
                  <ResponsiveAppBar />
                  {children}
                </main>
              </ThemeProviderCustom>
            </AuthProvider>
        </body>
      </html>
    
  )
}
